# Generated by Django 3.0.6 on 2020-05-25 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price_small', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_large', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('Regular Pizzas', 'Regular Pizzas'), ('Sicilian Pizzas', 'Sicilian Pizzas'), ('Subs', 'Subs'), ('Pastas', 'Pastas'), ('Salads', 'Salads'), ('Dinner Platters', 'Dinner Platters')], max_length=32)),
                ('num_toppings', models.IntegerField(default=0)),
                ('price_small', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_large', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Order_template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('extra_subs', models.ManyToManyField(blank=True, to='orders.ExtraSub')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='orders.Product')),
                ('toppings', models.ManyToManyField(blank=True, related_name='toppings', to='orders.Topping')),
            ],
        ),
        migrations.CreateModel(
            name='Order_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=32)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('all_products', models.ManyToManyField(blank=True, related_name='user_orders', to='orders.Order_template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usernames', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
